from __future__ import annotations

from typing import Any, Final, Generic, Iterable, Literal, Mapping, Protocol, Sequence, TypedDict, TypeVar
import sys
if sys.version_info >= (3, 11):
    from typing import NotRequired
else:
    try:
        from typing_extensions import NotRequired  # type: ignore
    except ImportError:
        # Keep generated stubs importable on Python versions whose stdlib typing
        # predates NotRequired and where typing_extensions is not installed. Type
        # checkers that understand the marker still get the precise form above; older
        # checkers see a regular generic compatibility marker instead of an import error.
        _ElisaNotRequiredT = TypeVar("_ElisaNotRequiredT")
        class NotRequired(Generic[_ElisaNotRequiredT]):
            pass



class ElisaError(RuntimeError):
    code: int
    function: str
    parameter: str | None
    expected: str | None
    path: str | None
    payload: Any

class DictBucket(TypedDict):
    key: Any
    value: Any
    state: int

class DictBucketInput(Protocol):
    key: Any
    value: Any
    state: int

class DynDict(TypedDict):
    items: Any
    count: int
    used: int
    capacity: int
    arena: int

class DynDictInput(Protocol):
    items: Any
    count: int
    used: int
    capacity: int
    arena: int

def count_i64(values: Mapping[int, int]) -> int: ...

def count_after_key(key: int, values: Mapping[int, int]) -> int: ...

def count_text(values: Mapping[str | bytes, int]) -> int: ...

def count_u64(values: Mapping[int, int]) -> int: ...

def count_float(values: Mapping[int, float]) -> int: ...

def count_bool(values: Mapping[str | bytes, bool]) -> int: ...

def count_bool_keys(values: Mapping[bool, int]) -> int: ...

def get_i64(values: Mapping[int, int], key: int) -> int: ...

def pair_count(left: Mapping[int, int], right: Mapping[str | bytes, bool]) -> int: ...

def empty_i64() -> dict[int, int]: ...

def roundtrip_i64(values: Mapping[int, int]) -> dict[int, int]: ...

def roundtrip_i32(values: Mapping[int, int]) -> dict[int, int]: ...

def roundtrip_u8(values: Mapping[str | bytes, int]) -> dict[str, int]: ...

def roundtrip_text(values: Mapping[str | bytes, bool]) -> dict[str, bool]: ...

def roundtrip_float(values: Mapping[int, float]) -> dict[int, float]: ...

def roundtrip_f32(values: Mapping[int, float]) -> dict[int, float]: ...

def roundtrip_u64(values: Mapping[int, int]) -> dict[int, int]: ...

def roundtrip_bool_keys(values: Mapping[bool, int]) -> dict[bool, int]: ...

def roundtrip_i8_keys(values: Mapping[int, int]) -> dict[int, int]: ...

def get_i8(values: Mapping[int, int], key: int) -> int: ...

def roundtrip_i16_keys(values: Mapping[int, int]) -> dict[int, int]: ...

def roundtrip_i32_keys(values: Mapping[int, int]) -> dict[int, int]: ...

def roundtrip_int_keys(values: Mapping[int, int]) -> dict[int, int]: ...

def roundtrip_isize_keys(values: Mapping[int, int]) -> dict[int, int]: ...

def roundtrip_char_keys(values: Mapping[int, int]) -> dict[int, int]: ...

def roundtrip_u8_keys(values: Mapping[int, int]) -> dict[int, int]: ...

def get_u8(values: Mapping[int, int], key: int) -> int: ...

def roundtrip_u16_keys(values: Mapping[int, int]) -> dict[int, int]: ...

def roundtrip_u32_keys(values: Mapping[int, int]) -> dict[int, int]: ...

def roundtrip_usize_keys(values: Mapping[int, int]) -> dict[int, int]: ...

def roundtrip_uintptr_keys(values: Mapping[int, int]) -> dict[int, int]: ...

def count_objects(values: Mapping[int, Any]) -> int: ...

def roundtrip_objects(values: Mapping[str | bytes, Any]) -> dict[str, Any]: ...

def roundtrip_cstr_values(values: Mapping[str | bytes, str | bytes]) -> dict[str, str]: ...

def roundtrip_sview_values(values: Mapping[int, str | bytes]) -> dict[int, str]: ...

def nested_count(values: Mapping[int, Sequence[int]]) -> int: ...

def roundtrip_nested(values: Mapping[int, Sequence[int]]) -> dict[int, list[int]]: ...

def roundtrip_nested_optional_scalars(values: Mapping[int, Sequence[int | None]]) -> dict[int, list[int | None]]: ...

def roundtrip_nested_optional_float(values: Mapping[str | bytes, Sequence[float | None]]) -> dict[str, list[float | None]]: ...

def roundtrip_nested_bytes(values: Mapping[str | bytes, bytes | bytearray | memoryview]) -> dict[str, bytes]: ...

def roundtrip_nested_objects(values: Mapping[int, Sequence[Any]]) -> dict[int, list[Any]]: ...

def roundtrip_nested_optional_objects(values: Mapping[int, Sequence[Any | None]]) -> dict[int, list[Any | None]]: ...

def roundtrip_nested_f32(values: Mapping[str | bytes, Sequence[float]]) -> dict[str, list[float]]: ...

def nested_float_count(values: Mapping[int, Sequence[float]]) -> int: ...

def roundtrip_nested_f64(values: Mapping[int, Sequence[float]]) -> dict[int, list[float]]: ...

def roundtrip_nested_i8(values: Mapping[int, Sequence[int]]) -> dict[int, list[int]]: ...

def roundtrip_nested_i16(values: Mapping[str | bytes, Sequence[int]]) -> dict[str, list[int]]: ...

def roundtrip_nested_i32(values: Mapping[int, Sequence[int]]) -> dict[int, list[int]]: ...

def roundtrip_nested_int(values: Mapping[int, Sequence[int]]) -> dict[int, list[int]]: ...

def roundtrip_nested_isize(values: Mapping[int, Sequence[int]]) -> dict[int, list[int]]: ...

def roundtrip_nested_char(values: Mapping[int, Sequence[int]]) -> dict[int, list[int]]: ...

def roundtrip_nested_u16(values: Mapping[int, Sequence[int]]) -> dict[int, list[int]]: ...

def roundtrip_nested_u32(values: Mapping[int, Sequence[int]]) -> dict[int, list[int]]: ...

def roundtrip_nested_u64(values: Mapping[int, Sequence[int]]) -> dict[int, list[int]]: ...

def roundtrip_nested_usize(values: Mapping[int, Sequence[int]]) -> dict[int, list[int]]: ...

def roundtrip_nested_uintptr(values: Mapping[int, Sequence[int]]) -> dict[int, list[int]]: ...

def roundtrip_nested_bool(values: Mapping[int, Sequence[bool]]) -> dict[int, list[bool]]: ...

def roundtrip_nested_cstr(values: Mapping[str | bytes, Sequence[str | bytes]]) -> dict[str, list[str]]: ...

def roundtrip_nested_sview(values: Mapping[int, Sequence[str | bytes]]) -> dict[int, list[str]]: ...

def roundtrip_nested_optional_cstr(values: Mapping[str | bytes, Sequence[str | bytes | None]]) -> dict[str, list[str | None]]: ...

def roundtrip_nested_optional_sview(values: Mapping[int, Sequence[str | bytes | None]]) -> dict[int, list[str | None]]: ...

__all__: list[str] = ["count_i64", "count_after_key", "count_text", "count_u64", "count_float", "count_bool", "count_bool_keys", "get_i64", "pair_count", "empty_i64", "roundtrip_i64", "roundtrip_i32", "roundtrip_u8", "roundtrip_text", "roundtrip_float", "roundtrip_f32", "roundtrip_u64", "roundtrip_bool_keys", "roundtrip_i8_keys", "get_i8", "roundtrip_i16_keys", "roundtrip_i32_keys", "roundtrip_int_keys", "roundtrip_isize_keys", "roundtrip_char_keys", "roundtrip_u8_keys", "get_u8", "roundtrip_u16_keys", "roundtrip_u32_keys", "roundtrip_usize_keys", "roundtrip_uintptr_keys", "count_objects", "roundtrip_objects", "roundtrip_cstr_values", "roundtrip_sview_values", "nested_count", "roundtrip_nested", "roundtrip_nested_optional_scalars", "roundtrip_nested_optional_float", "roundtrip_nested_bytes", "roundtrip_nested_objects", "roundtrip_nested_optional_objects", "roundtrip_nested_f32", "nested_float_count", "roundtrip_nested_f64", "roundtrip_nested_i8", "roundtrip_nested_i16", "roundtrip_nested_i32", "roundtrip_nested_int", "roundtrip_nested_isize", "roundtrip_nested_char", "roundtrip_nested_u16", "roundtrip_nested_u32", "roundtrip_nested_u64", "roundtrip_nested_usize", "roundtrip_nested_uintptr", "roundtrip_nested_bool", "roundtrip_nested_cstr", "roundtrip_nested_sview", "roundtrip_nested_optional_cstr", "roundtrip_nested_optional_sview", "ElisaError", "DictBucket", "DynDict"]
