// Generate the Stage1 lexer ranges from the Go Unicode tables used by Stage0.
// Run from the compiler repository root:
//
//	go run test/parity/generate_lexer_unicode_ranges.go > src/lexer/lexer_unicode_ranges.elisa
package main

import (
	"fmt"
	"unicode"
)

type codepointRange struct {
	first rune
	last  rune
}

const (
	firstThreeByteCodepoint = 0x800
	lastBMPCodepoint        = 0xFFFF
	rangesPerPredicate      = 12
)

func collectRanges(classify func(rune) bool) []codepointRange {
	ranges := make([]codepointRange, 0)
	inside := false
	var start rune
	for codepoint := rune(firstThreeByteCodepoint); codepoint <= lastBMPCodepoint; codepoint++ {
		if classify(codepoint) {
			if !inside {
				start = codepoint
				inside = true
			}
		} else if inside {
			ranges = append(ranges, codepointRange{first: start, last: codepoint - 1})
			inside = false
		}
	}
	if inside {
		ranges = append(ranges, codepointRange{first: start, last: lastBMPCodepoint})
	}
	return ranges
}

func emitPredicate(prefix, name string, ranges []codepointRange) {
	groupCount := (len(ranges) + rangesPerPredicate - 1) / rangesPerPredicate
	for group := 0; group < groupCount; group++ {
		start := group * rangesPerPredicate
		stop := start + rangesPerPredicate
		if stop > len(ranges) {
			stop = len(ranges)
		}
		fmt.Printf("        def %s_%02d(value: int) -> bool:\n", prefix, group)
		fmt.Print("            return ")
		for index, interval := range ranges[start:stop] {
			if index > 0 {
				fmt.Print(" or ")
			}
			if interval.first == interval.last {
				fmt.Printf("value == 0x%X", interval.first)
			} else {
				fmt.Printf("value in 0x%X..0x%X", interval.first, interval.last)
			}
		}
		fmt.Println()
	}

	fmt.Printf("        def %s(value: int) -> bool:\n", name)
	if groupCount == 0 {
		fmt.Println("            return false")
		return
	}
	fmt.Print("            return ")
	for group := 0; group < groupCount; group++ {
		if group > 0 {
			fmt.Print(" or ")
		}
		fmt.Printf("%s_%02d(value)", prefix, group)
	}
	fmt.Println()
}

func main() {
	fmt.Printf("# Generated by test/parity/generate_lexer_unicode_ranges.go; Unicode %s.\n", unicode.Version)
	fmt.Println("# Keep these predicates aligned with the Go unicode tables used by the Stage0 lexer.")
	fmt.Println("extend Lexer:")
	fmt.Println("    private:")
	emitPredicate("unicode3_letter_range", "is_unicode3_letter_codepoint", collectRanges(unicode.IsLetter))
	emitPredicate("unicode3_digit_range", "is_unicode3_digit_codepoint", collectRanges(unicode.IsDigit))
}
