#!/usr/bin/env python3
"""The zero-glue ESM and TypeScript FACADE: JS conversions per ABI type, the `.mjs` loader,
and the `.d.ts` declarations.

Split out of wasm_build.py.  Every byte here is compared against the driver's own port in
src/driver/emit_wasm_facade.elisa by test/parity/wasm_python_parity_smoke.sh, so a change on
one side has to be made on the other.
"""

from __future__ import annotations

import json
import re
from typing import Any

from scripts.wasm_export_scan import normalize_type

def ts_type(type_text: str, target: str, *, parameter: bool = False) -> str:
    normalized = normalize_type(type_text)
    if normalized == "cstr":
        return "string | number" if parameter else "string"
    if normalized in {"i64", "u64", "int", "char"}:
        return "bigint"
    if normalized in {"bool"}:
        return "boolean"
    if normalized == "void":
        return "void"
    return "number"


def js_input(type_text: str, expression: str) -> str:
    normalized = normalize_type(type_text)
    if normalized in {"i64", "u64", "int", "char"}:
        return f"BigInt({expression})"
    if normalized == "bool":
        return f"{expression} ? 1 : 0"
    return expression


def js_output(type_text: str, expression: str) -> str:
    normalized = normalize_type(type_text)
    if normalized == "cstr":
        return f"memoryTools.readString({expression})"
    if normalized == "bool":
        return f"!!({expression})"
    if normalized == "i8":
        return f"(({expression} << 24) >> 24)"
    if normalized == "i16":
        return f"(({expression} << 16) >> 16)"
    if normalized in {"isize"}:
        return f"(({expression}) | 0)"
    if normalized == "u8":
        return f"(({expression}) & 0xff)"
    if normalized == "u16":
        return f"(({expression}) & 0xffff)"
    if normalized in {"u32", "usize", "uintptr"}:
        return f"(({expression}) >>> 0)"
    return expression


def js_bindings(manifest: dict[str, Any], module_name: str) -> str:
    functions: list[str] = []
    for item in manifest["exports"]:
        args = ", ".join(parameter["name"] for parameter in item["parameters"])
        raw_arguments: list[str] = []
        setup: list[str] = []
        cleanup: list[str] = []
        for parameter in item["parameters"]:
            parameter_name = parameter["name"]
            if parameter["binding"] == "string":
                local_name = f"__elisa_{parameter_name}"
                setup.append(
                    f"      const {local_name} = typeof {parameter_name} === \"string\" "
                    f"? memoryTools.writeString({parameter_name}) : ({parameter_name} >>> 0);"
                )
                cleanup.append(f"        if (typeof {parameter_name} === \"string\") memoryTools.free({local_name});")
                raw_arguments.append(local_name)
            else:
                raw_arguments.append(js_input(parameter["type"], parameter_name))
        raw_args = ", ".join(raw_arguments)
        call = f"instance.exports[{json.dumps(item['name'])}]({raw_args})"
        result = js_output(item["return"], call)
        if setup:
            functions.append(
                f"    {item['name']}({args}) {{\n"
                + "\n".join(setup)
                + f"\n      try {{ return {result}; }}\n"
                + "      finally {\n"
                + "\n".join(cleanup)
                + "\n      }\n"
                + "    }"
            )
        else:
            functions.append(f"    {item['name']}({args}) {{ return {result}; }}")
    function_block = ",\n".join(functions)
    wasm_relative_url = json.dumps(f"./{manifest['files']['wasm']}")
    return f'''// Generated by `elisac -emit wasm`; edit the Elisa source, not this file.
const WASM_URL = new URL({wasm_relative_url}, import.meta.url);
const PAGE_SIZE = 65536;
const DEFAULT_INITIAL_PAGES = {manifest["memory_initial_pages"]};
const DEFAULT_MAXIMUM_PAGES = {manifest["memory_max_pages"]};
const RUNTIME_STATE = Symbol("ElisaWasmRuntimeState");
const UTF8_ENCODER = new TextEncoder();
const UTF8_DECODER = new TextDecoder();

function align(value, boundary = 16) {{ return (value + boundary - 1) & ~(boundary - 1); }}

/** Create the small host ABI used by Elisa's portable runtime. User imports win. */
export function createElisaImports(options = {{}}) {{
  const customImports = options.imports ?? {{}};
  const customEnv = customImports.env ?? {{}};
  const memory = options.memory ?? customEnv.memory ?? new WebAssembly.Memory({{ initial: options.initialPages ?? DEFAULT_INITIAL_PAGES, maximum: options.maximumPages ?? DEFAULT_MAXIMUM_PAGES }});
  if (!(memory instanceof WebAssembly.Memory)) throw new TypeError("Elisa WASM requires options.memory/imports.env.memory to be a WebAssembly.Memory");
  let next = options.heapBase === undefined ? 0 : align(Number(options.heapBase));
  let heapReady = options.heapBase !== undefined;
  const allocations = new Map();
  const freeBlocks = [];
  const bytes = () => new Uint8Array(memory.buffer);
  const ensureEnd = (end) => {{
    while (end > memory.buffer.byteLength) memory.grow(Math.max(1, Math.ceil((end - memory.buffer.byteLength) / PAGE_SIZE)));
  }};
  const readCString = (pointer) => {{
    if (!pointer) return "";
    const data = bytes(); let end = pointer >>> 0;
    while (end < data.length && data[end] !== 0) end++;
    return UTF8_DECODER.decode(data.subarray(pointer >>> 0, end));
  }};
  const coalesceFreeBlocks = () => {{
    freeBlocks.sort((left, right) => left.pointer - right.pointer);
    for (let index = 1; index < freeBlocks.length;) {{
      const previous = freeBlocks[index - 1], current = freeBlocks[index];
      if (previous.pointer + previous.size === current.pointer) {{
        previous.size += current.size;
        freeBlocks.splice(index, 1);
      }} else index++;
    }}
  }};
  const setHeapBase = (value) => {{
    const base = align(Number(value));
    next = Math.max(next, base);
    heapReady = true;
  }};
  const malloc = (requestedSize) => {{
    if (!heapReady) throw new Error("Elisa WASM allocator used before __heap_base was initialized");
    const numericSize = Number(requestedSize);
    if (!Number.isSafeInteger(numericSize) || numericSize < 0) throw new RangeError(`Invalid Elisa WASM allocation size: ${{requestedSize}}`);
    const size = align(Math.max(1, numericSize));
    const reusable = freeBlocks.findIndex((block) => block.size >= size);
    if (reusable >= 0) {{
      const block = freeBlocks[reusable];
      const pointer = block.pointer;
      if (block.size === size) freeBlocks.splice(reusable, 1);
      else {{ block.pointer += size; block.size -= size; }}
      allocations.set(pointer, size);
      return pointer;
    }}
    const pointer = align(next);
    next = pointer + size;
    ensureEnd(next);
    allocations.set(pointer, size);
    return pointer;
  }};
  const free = (rawPointer) => {{
    const pointer = Number(rawPointer) >>> 0;
    const size = allocations.get(pointer);
    if (size === undefined) return;
    allocations.delete(pointer);
    freeBlocks.push({{ pointer, size }});
    coalesceFreeBlocks();
  }};
  const writeBytes = (value, nulTerminate = false) => {{
    const source = value instanceof Uint8Array
      ? Uint8Array.from(value)
      : Uint8Array.from(new Uint8Array(value.buffer ?? value, value.byteOffset ?? 0, value.byteLength ?? value.length));
    const pointer = malloc(source.byteLength + (nulTerminate ? 1 : 0));
    bytes().set(source, pointer);
    if (nulTerminate) bytes()[pointer + source.byteLength] = 0;
    return Object.freeze({{ pointer, length: source.byteLength }});
  }};
  const readBytes = (pointer, length) => bytes().slice(pointer >>> 0, (pointer >>> 0) + Number(length));
  const writeString = (text) => writeBytes(UTF8_ENCODER.encode(String(text)), true).pointer;
  const onWrite = options.onWrite ?? ((text, descriptor) => (descriptor === 2 ? console.error(text) : console.log(text)));
  const env = {{
    memory,
    stderr: new WebAssembly.Global({{ value: "i32", mutable: false }}, 0),
    malloc,
    free,
    realloc(pointer, oldSize, newSize) {{ if (!pointer) return malloc(newSize); if (Number(newSize) === 0) {{ free(pointer); return 0; }} const available = allocations.get(pointer >>> 0) ?? Number(oldSize); const replacement = malloc(newSize); new Uint8Array(memory.buffer, replacement, Number(newSize)).set(new Uint8Array(memory.buffer, pointer >>> 0, Math.min(available, Number(newSize)))); free(pointer); return replacement; }},
    memcpy(destination, source, size) {{ new Uint8Array(memory.buffer, destination >>> 0, Number(size)).set(new Uint8Array(memory.buffer, source >>> 0, Number(size))); return destination; }},
    memmove(destination, source, size) {{ const copy = new Uint8Array(memory.buffer, source >>> 0, Number(size)).slice(); new Uint8Array(memory.buffer, destination >>> 0, Number(size)).set(copy); return destination; }},
    memset(destination, value, size) {{ bytes().fill(Number(value) & 255, destination >>> 0, (destination >>> 0) + Number(size)); return destination; }},
    memcmp(left, right, size) {{ const data = bytes(); for (let i = 0; i < Number(size); i++) {{ const difference = data[(left >>> 0) + i] - data[(right >>> 0) + i]; if (difference) return difference; }} return 0; }},
    strlen(pointer) {{ let length = 0; const data = bytes(); while (data[(pointer >>> 0) + length] !== 0) length++; return length; }},
    strcmp(left, right) {{ const a = readCString(left), b = readCString(right); return a < b ? -1 : (a > b ? 1 : 0); }},
    puts(pointer) {{ (options.onPrint ?? ((text) => console.log(text)))(readCString(pointer)); return 0; }},
    write(descriptor, pointer, size) {{ onWrite(UTF8_DECODER.decode(readBytes(pointer, size)), Number(descriptor)); return Number(size); }},
    read() {{ return -1; }},
    printf(format) {{ const text = readCString(format); (options.onPrint ?? ((line) => console.log(line)))(text); return UTF8_ENCODER.encode(text).byteLength; }},
    fprintf() {{ return 0; }},
    snprintf() {{ return -1; }},
    backtrace() {{ return 0; }},
    backtrace_symbols_fd() {{}},
    wasm_memory_size() {{ return memory.buffer.byteLength / PAGE_SIZE; }},
    wasm_memory_grow(index, pages) {{ try {{ return memory.grow(Number(pages)); }} catch {{ return -1; }} }},
    abort() {{ throw new Error("Elisa WASM aborted"); }},
    exit(code) {{ throw new Error(`Elisa WASM exited with code ${{code}}`); }},
  }};
  const imports = {{ ...customImports, memory, env: {{ ...env, ...customEnv, ...(options.env ?? {{}}), memory }} }};
  Object.defineProperty(imports, RUNTIME_STATE, {{ value: {{ setHeapBase, malloc, free, writeBytes, readBytes, writeString, readString: readCString }} }});
  return imports;
}}

async function sourceBytes(source) {{
  if (typeof Response !== "undefined" && source instanceof Response) return new Uint8Array(await source.arrayBuffer());
  if (source instanceof ArrayBuffer) return new Uint8Array(source);
  if (ArrayBuffer.isView(source)) return new Uint8Array(source.buffer, source.byteOffset, source.byteLength);
  const url = source instanceof URL ? source : (source ? String(source) : WASM_URL);
  if (url instanceof URL && url.protocol === "file:") {{
    const {{ readFile }} = await import("node:fs/promises");
    return new Uint8Array(await readFile(url));
  }}
  if (typeof url === "string" && url.startsWith("file:")) {{
    const {{ readFile }} = await import("node:fs/promises");
    return new Uint8Array(await readFile(new URL(url)));
  }}
  if (typeof url === "string" && !/^(?:https?:|file:)/.test(url)) {{
    try {{ const {{ readFile }} = await import("node:fs/promises"); return new Uint8Array(await readFile(url)); }} catch {{ /* browser URL fallback */ }}
  }}
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Unable to load Elisa WASM (${{response.status}} ${{response.statusText}}): ${{response.url || url}}`);
  return new Uint8Array(await response.arrayBuffer());
}}

export async function loadWasm(source, options = {{}}) {{
  const imports = createElisaImports(options);
  const module = await WebAssembly.compile(await sourceBytes(source));
  const missing = WebAssembly.Module.imports(module).filter((required) => !(required.name in (imports[required.module] ?? {{}})));
  if (missing.length) {{
    const names = missing.map((required) => `${{required.module}}.${{required.name}} (${{required.kind}})`).join(", ");
    throw new Error(`Missing Elisa WASM imports: ${{names}}. Provide them through loadWasm(source, {{ imports: {{ module: {{ name: value }} }} }}).`);
  }}
  const instance = await WebAssembly.instantiate(module, imports);
  const runtime = imports[RUNTIME_STATE];
  const heapGlobal = instance.exports.__heap_base;
  const heapBase = heapGlobal instanceof WebAssembly.Global ? heapGlobal.value : heapGlobal;
  if (heapBase === undefined) throw new Error("Elisa WASM module does not export __heap_base");
  runtime.setHeapBase(heapBase);
  const memoryTools = Object.freeze({{
    alloc: runtime.malloc,
    free: runtime.free,
    writeBytes: runtime.writeBytes,
    readBytes: runtime.readBytes,
    writeString: runtime.writeString,
    readString: runtime.readString,
  }});
  return Object.freeze({{
{function_block},
    memory: imports.memory,
    ...memoryTools,
    raw: instance.exports,
  }});
}}

export default loadWasm;
'''


def type_declaration(manifest: dict[str, Any], module_name: str) -> str:
    interface_stem = re.sub(r"[^A-Za-z0-9_$]", "_", module_name)
    if not interface_stem or interface_stem[0].isdigit():
        interface_stem = f"_{interface_stem}"
    interface_name = f"{interface_stem}Exports"
    interfaces: list[str] = []
    for item in manifest["exports"]:
        params = ", ".join(f"{p['name']}: {ts_type(p['type'], manifest['target'], parameter=True)}" for p in item["parameters"])
        interfaces.append(f"  {item['name']}({params}): {ts_type(item['return'], manifest['target'])};")
    return f'''// Generated by `elisac -emit wasm`; edit the Elisa source, not this file.
export type WasmSource = string | URL | ArrayBuffer | ArrayBufferView | Response;
export interface ElisaWasmLoadOptions {{
  memory?: WebAssembly.Memory;
  initialPages?: number;
  maximumPages?: number;
  heapBase?: number;
  imports?: WebAssembly.Imports;
  env?: Record<string, unknown>;
  onPrint?: (text: string) => void;
  onWrite?: (text: string, descriptor: number) => void;
}}
export interface ElisaWasmBuffer {{ readonly pointer: number; readonly length: number; }}
export interface {interface_name} {{
{chr(10).join(interfaces)}
  memory: WebAssembly.Memory;
  alloc(size: number): number;
  free(pointer: number): void;
  writeBytes(data: ArrayBuffer | ArrayBufferView): ElisaWasmBuffer;
  readBytes(pointer: number, length: number): Uint8Array;
  writeString(text: string): number;
  readString(pointer: number): string;
  raw: Record<string, unknown>;
}}
export function createElisaImports(options?: ElisaWasmLoadOptions): WebAssembly.Imports;
export function loadWasm(source?: WasmSource, options?: ElisaWasmLoadOptions): Promise<{interface_name}>;
export default loadWasm;
'''


