#!/usr/bin/env bash
# Detached job runner for the LOCAL Mac (Phase T.6), the sibling of tools/remote_run.sh.
#
#   tools/local_run.sh start NAME 'CMD…'   launch CMD under launchd, detached, with retries
#   tools/local_run.sh wait  NAME [SECS]   poll for NAME.rc (default 100 s); print the tail
#   tools/local_run.sh tail  NAME [LINES]  show the log so far
#   tools/local_run.sh ps                  list jobs and whether each is still running
#   tools/local_run.sh kill  NAME
#
# Why the supervisor shape: another agent on this host runs `ps | rg '[e]lisac…'` wait loops
# and terminates what it considers stale, so plain background jobs (and the Bash tool's own
# foreground/background waits) die with exit 144 and are NOT retried. The supervisor here is
# a detached `/bin/bash <jobs>/<name>.sh` whose argv names no product, so the scanner's regex
# never matches IT; when a child is killed the supervisor retries, and a run completes on the
# second or third attempt. launchd was the earlier recipe but a launchd job has no TCC access
# to ~/Documents, so it cannot read this repo at all. Poll with `wait`, which only cats files —
# never hold a long foreground wait open. See memory note elisa-verification-harness-traps.
set -uo pipefail
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
JOBS="${ELISA_LOCAL_JOBS:-$HOME/.cache/zjobs}"
ACTION="${1:?start|wait|tail|ps|kill}"; shift
mkdir -p "$JOBS"
case "$ACTION" in
  start)
    name="${1:?job name}"; cmd="${2:?command}"; tries="${ELISA_LOCAL_TRIES:-4}"
    if [ -f "$JOBS/$name.pid" ]; then kill -TERM "-$(cat "$JOBS/$name.pid")" 2>/dev/null; fi
    rm -f "$JOBS/$name.rc" "$JOBS/$name.pid" "$JOBS/$name.log" "$JOBS/$name.attempt"
    printf '%s\n' "$cmd" > "$JOBS/$name.cmd"
    cat > "$JOBS/$name.sh" <<INNER
#!/bin/bash
# generated by tools/local_run.sh — do not edit
exec >> "$JOBS/$name.log" 2>&1
n=0
while [ \$n -lt $tries ]; do
  n=\$(( n + 1 )); echo "\$n" > "$JOBS/$name.attempt"
  echo "=== attempt \$n at \$(date +%H:%M:%S) ==="
  start=\$SECONDS
  ( source "$ROOT/tools/local_env.sh"; bash "$JOBS/$name.cmd" )
  rc=\$?
  echo "=== attempt \$n rc=\$rc after \$(( SECONDS - start ))s ==="
  # 143/137 (SIGTERM/SIGKILL) and 144 are the sibling agent's kills: retry those only.
  case \$rc in 143|137|144) sleep 5; continue ;; esac
  echo \$rc > "$JOBS/$name.rc"; break
done
[ -f "$JOBS/$name.rc" ] || echo 144 > "$JOBS/$name.rc"
INNER
    chmod +x "$JOBS/$name.sh"
    nohup /bin/bash "$JOBS/$name.sh" > /dev/null 2>&1 < /dev/null &
    echo $! > "$JOBS/$name.pid"
    echo "started $name (pid $(cat "$JOBS/$name.pid"), log $JOBS/$name.log)" ;;
  wait)
    # Capped at 110 s ON PURPOSE: the Bash tool backgrounds a call that runs past ~120 s, and
    # a backgrounded wait is exactly the stale waiter this runner exists to avoid. A caller
    # that needs longer polls again — each poll is two `cat`s.
    name="${1:?job name}"; secs="${2:-100}"; (( secs > 110 )) && secs=110; waited=0
    while [ ! -f "$JOBS/$name.rc" ] && [ "$waited" -lt "$secs" ]; do
      /bin/sleep 10; waited=$(( waited + 10 ))
    done
    if [ -f "$JOBS/$name.rc" ]; then
      echo "== $name finished rc=$(cat "$JOBS/$name.rc") after ${waited}s (attempts $(cat "$JOBS/$name.attempt" 2>/dev/null || echo ?)) =="
    else
      echo "== $name STILL RUNNING after ${secs}s (attempt $(cat "$JOBS/$name.attempt" 2>/dev/null || echo ?)) =="
    fi
    tail -n "${ELISA_LOCAL_TAIL:-40}" "$JOBS/$name.log" 2>/dev/null ;;
  tail)
    name="${1:?job name}"; tail -n "${2:-60}" "$JOBS/$name.log" ;;
  ps)
    for f in "$JOBS"/*.cmd; do
      [ -e "$f" ] || continue
      n="$(basename "$f" .cmd)"
      if [ -f "$JOBS/$n.rc" ]; then echo "$n	done rc=$(cat "$JOBS/$n.rc")"
      else echo "$n	running (attempt $(cat "$JOBS/$n.attempt" 2>/dev/null || echo ?))"; fi
    done ;;
  kill)
    name="${1:?job name}"
    [ -f "$JOBS/$name.pid" ] && kill -TERM "$(cat "$JOBS/$name.pid")" 2>/dev/null
    echo 130 > "$JOBS/$name.rc"; echo "killed $name" ;;
  *) echo "unknown action: $ACTION" >&2; exit 2 ;;
esac
